<?php

// Route table: [HTTP method, path pattern, Controller@action].
// {param} segments are captured and passed to the action by name.

return [
    // Public (guests can reach these)
    ['GET', '/health', 'HealthController@show'],
    ['GET', '/', 'AuthController@loginForm'],
    ['GET', '/terms', 'StaticPageController@terms'],
    ['GET', '/privacy', 'StaticPageController@privacy'],
    ['GET', '/about', 'StaticPageController@about'],
    ['GET', '/galleries', 'GalleryController@index'],
    ['GET', '/galleries/category/{slug}', 'GalleryController@category'],
    ['GET', '/galleries/{id}/photos', 'GalleryController@photosPage'],
    ['GET', '/galleries/{id}', 'GalleryController@show'],
    ['GET', '/images/{id}', 'ImageController@show'],
    ['GET', '/videos/{id}', 'VideoController@show'],
    ['GET', '/files/{file}', 'StorageController@serve'],

    // Biller postbacks (server-to-server; no session, no CSRF — see Router)
    ['GET', '/webhooks/{provider}', 'WebhookController@handle'],
    ['POST', '/webhooks/{provider}', 'WebhookController@handle'],

    // Auth
    ['GET', '/login', 'AuthController@loginForm'],
    ['POST', '/login', 'AuthController@login'],
    ['GET', '/signup', 'AuthController@signupForm'],
    ['POST', '/signup', 'AuthController@signup'],
    ['GET', '/verify-email', 'AuthController@verifyEmail'],
    ['POST', '/verify-email/resend', 'AuthController@resendVerification'],
    ['POST', '/logout', 'AuthController@logout'],
    ['GET', '/forgot-password', 'AuthController@forgotForm'],
    ['POST', '/forgot-password', 'AuthController@forgot'],
    ['GET', '/reset-password', 'AuthController@resetForm'],
    ['POST', '/reset-password', 'AuthController@reset'],

    // Favorites (logged in)
    ['GET', '/favorites', 'FavoriteController@index'],
    ['POST', '/favorites/categories/{categoryId}/toggle', 'FavoriteController@toggle'],
    ['POST', '/favorites/galleries/{galleryId}/toggle', 'FavoriteController@toggleGallery'],

    // Saved searches (active members)
    ['GET', '/saved-searches', 'SavedSearchController@index'],
    ['POST', '/saved-searches', 'SavedSearchController@store'],
    ['POST', '/saved-searches/{id}/delete', 'SavedSearchController@destroy'],

    // Support (logged in)
    ['GET', '/support', 'SupportController@form'],
    ['POST', '/support', 'SupportController@submit'],
    ['GET', '/support/{id}', 'SupportController@show'],
    ['POST', '/support/{id}/reply', 'SupportController@reply'],

    // Admin
    ['GET', '/admin', 'AdminController@dashboard'],
    ['POST', '/admin', 'AdminController@login'],
    ['GET', '/admin/abandoned-uploads', 'AdminController@abandonedUploads'],
    ['POST', '/admin/abandoned-uploads/resume', 'AdminController@resumeAbandoned'],
    ['GET', '/admin/abandoned-uploads/{session}/{file}', 'AdminController@abandonedFile'],
    ['POST', '/admin/abandoned-uploads/{session}/{file}', 'AdminController@assignAbandoned'],
    ['GET', '/admin/search', 'SearchController@index'],
    ['GET', '/admin/categories', 'CategoryController@index'],
    ['POST', '/admin/categories', 'CategoryController@store'],
    ['GET', '/admin/categories/{id}/edit', 'CategoryController@edit'],
    ['POST', '/admin/categories/{id}', 'CategoryController@update'],
    ['POST', '/admin/categories/{id}/delete', 'CategoryController@destroy'],
    ['GET', '/admin/galleries', 'GalleryController@index'],
    ['GET', '/admin/galleries/create', 'GalleryController@create'],
    ['POST', '/admin/galleries/pending/upload', 'GalleryController@pendingUpload'],
    ['POST', '/admin/galleries/pending/{file}/rotate', 'GalleryController@pendingRotate'],
    ['POST', '/admin/galleries/pending/{file}/delete', 'GalleryController@pendingDelete'],
    ['GET', '/admin/galleries/pending/{file}', 'GalleryController@pendingFile'],
    ['POST', '/admin/galleries', 'GalleryController@store'],
    ['GET', '/admin/galleries/{id}', 'AdminController@manageGallery'],
    ['GET', '/admin/galleries/{id}/edit', 'GalleryController@edit'],
    ['POST', '/admin/galleries/bulk', 'GalleryController@bulk'],
    ['POST', '/admin/galleries/{id}', 'GalleryController@update'],
    ['POST', '/admin/galleries/{id}/delete', 'GalleryController@destroy'],
    ['POST', '/admin/galleries/{galleryId}/photos', 'PhotoController@upload'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/caption', 'PhotoController@updateCaption'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/delete', 'PhotoController@destroy'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/move', 'PhotoController@move'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/rotate', 'PhotoController@rotate'],
    ['POST', '/admin/galleries/{galleryId}/photos/bulk-rotate', 'PhotoController@bulkRotate'],
    ['GET', '/admin/photos/{id}/edit', 'PhotoController@edit'],
    ['POST', '/admin/photos/{id}/edit', 'PhotoController@applyEdit'],
    ['GET', '/admin/videos/{id}/edit', 'VideoEditorController@edit'],
    ['GET', '/admin/videos', 'VideoEditorController@videoList'],
    ['GET', '/admin/video-projects', 'VideoEditorController@dashboard'],
    ['POST', '/admin/video-projects/{id}', 'VideoEditorController@save'],
    ['POST', '/admin/video-projects/{id}/export', 'VideoEditorController@export'],
    ['GET', '/admin/video-exports/{id}', 'VideoEditorController@status'],
    ['GET', '/admin/video-exports/{id}/stream', 'VideoEditorController@stream'],
    ['GET', '/admin/video-exports/{id}/download', 'VideoEditorController@download'],
    ['POST', '/admin/video-exports/{id}/delete', 'VideoEditorController@deleteExport'],
    ['POST', '/admin/video-exports/{id}/purge', 'VideoEditorController@purgeExport'],
    ['GET', '/admin/video-exports/{id}/create-gallery', 'VideoEditorController@createGalleryFromExport'],
    ['POST', '/admin/video-exports/{id}/create-gallery', 'VideoEditorController@createGalleryFromExport'],

    // Users (admin only)
    ['GET', '/admin/users', 'UserController@index'],
    ['GET', '/admin/users/create', 'UserController@create'],
    ['POST', '/admin/users', 'UserController@store'],
    ['POST', '/admin/users/bulk', 'UserController@bulk'],
    ['POST', '/admin/users/{id}/impersonate', 'UserController@impersonate'],
    ['POST', '/admin/users/{id}/status', 'UserController@setStatus'],
    ['POST', '/admin/users/{id}/reset-password', 'UserController@resetPassword'],
    ['POST', '/admin/users/{id}/logout-everywhere', 'UserController@logoutEverywhere'],
    ['POST', '/admin/users/{id}/notes', 'UserController@addNote'],
    ['POST', '/admin/users/{id}/flag', 'UserController@setFlag'],
    ['POST', '/admin/users/{id}/role', 'UserController@updateRole'],
    ['GET', '/admin/users/{id}/edit', 'UserController@edit'],
    ['POST', '/admin/users/{id}', 'UserController@update'],
    ['POST', '/admin/users/{id}/delete', 'UserController@destroy'],
    ['GET', '/admin/users/{id}', 'UserController@show'],
    ['POST', '/admin/impersonate/exit', 'UserController@exitImpersonation'],

    // System maintenance (admin only)
    ['GET', '/admin/system', 'SystemController@index'],
    ['POST', '/admin/system/cleanup/pending', 'SystemController@cleanupPending'],
    ['POST', '/admin/system/cleanup/orphans', 'SystemController@cleanupOrphans'],
    ['POST', '/admin/system/backup', 'SystemController@backupCreate'],
    ['GET', '/admin/system/backups/{file}', 'SystemController@backupDownload'],
    ['POST', '/admin/system/backups/{file}/delete', 'SystemController@backupDelete'],
    ['POST', '/admin/system/variants', 'SystemController@variantsRegenerate'],
    ['POST', '/admin/system/db/optimize', 'SystemController@dbOptimize'],
    ['POST', '/admin/system/maintenance', 'SystemController@maintenanceToggle'],
    ['POST', '/admin/system/housekeeping', 'SystemController@housekeepingRun'],
    ['POST', '/admin/system/smtp-test', 'SystemController@smtpTest'],
    ['GET', '/admin/export/users', 'ExportController@users'],
    ['GET', '/admin/export/subscriptions', 'ExportController@subscriptions'],

    // Unattended cron (secret-key protected, no session)
    ['GET', '/cron/housekeeping', 'CronController@run'],

    // Theme + docs (admin only)
    ['GET', '/admin/theme', 'ThemeController@index'],
    ['POST', '/admin/theme', 'ThemeController@update'],
    ['POST', '/admin/theme/presets/save', 'ThemeController@savePreset'],
    ['POST', '/admin/theme/presets/apply', 'ThemeController@applyPreset'],
    ['POST', '/admin/theme/presets/delete', 'ThemeController@deletePreset'],
    ['GET', '/admin/site-editor', 'SiteEditorController@editor'],
    ['GET', '/admin/site-editor/templates', 'SiteEditorController@templates'],
    ['POST', '/admin/site-editor/save', 'SiteEditorController@save'],
    ['POST', '/admin/site-editor/update/{id}', 'SiteEditorController@update'],
    ['POST', '/admin/site-editor/delete/{id}', 'SiteEditorController@delete'],
    ['POST', '/admin/site-editor/activate/{id}', 'SiteEditorController@activate'],
    ['POST', '/admin/site-editor/deactivate', 'SiteEditorController@deactivate'],
    ['GET', '/admin/help', 'HelpController@index'],
    ['GET', '/admin/support', 'SupportController@index'],
    ['GET', '/admin/support/{id}', 'SupportController@adminShow'],
    ['POST', '/admin/support/{id}/reply', 'SupportController@adminReply'],
    ['POST', '/admin/support/{id}/status', 'SupportController@status'],
    ['POST', '/admin/support/{id}/delete', 'SupportController@delete'],
    ['GET', '/admin/trends', 'TrendsController@index'],
    ['POST', '/admin/trends/promote', 'TrendsController@approvePromotion'],
    ['POST', '/admin/trends/dismiss', 'TrendsController@dismissPromotion'],
    ['GET', '/admin/logs', 'LogsController@index'],
    ['GET', '/admin/error-logs', 'LogsController@errorIndex'],
    ['POST', '/admin/logs/{id}/rollback', 'LogsController@rollback'],
    ['POST', '/admin/logs/{id}/purge', 'LogsController@purgeGallery'],

    // Settings (logged in)
    ['GET', '/settings', 'SettingsController@show'],
    ['POST', '/settings/password', 'SettingsController@updatePassword'],
    ['POST', '/settings/profile', 'SettingsController@updateProfile'],
    ['POST', '/settings/logout-everywhere', 'SettingsController@logoutEverywhere'],
    ['POST', '/settings/favorites', 'SettingsController@updateFavorites'],
    ['POST', '/settings/theme', 'SettingsController@updateTheme'],

    // Membership (logged in)
    ['GET', '/account', 'MembershipController@dashboard'],
    ['GET', '/membership', 'MembershipController@index'],
    ['GET', '/membership/my', 'MembershipController@my'],
    ['POST', '/membership/subscribe', 'MembershipController@subscribe'],
    ['POST', '/membership/cancel', 'MembershipController@cancel'],
    ['POST', '/membership/paypal-approve', 'MembershipController@paypalApprove'],
    ['GET', '/membership/checkout', 'MembershipController@braintreeCheckout'],
    ['GET', '/membership/braintree-token', 'MembershipController@braintreeToken'],
    ['POST', '/membership/braintree-token', 'MembershipController@braintreeToken'],

    // Plans (admin only)
    ['GET', '/admin/plans', 'PlanController@index'],
    ['GET', '/admin/plans/create', 'PlanController@create'],
    ['POST', '/admin/plans', 'PlanController@store'],
    ['GET', '/admin/plans/{id}/edit', 'PlanController@edit'],
    ['POST', '/admin/plans/{id}', 'PlanController@update'],
    ['POST', '/admin/plans/{id}/delete', 'PlanController@destroy'],
    ['POST', '/admin/plans/{id}/toggle-active', 'PlanController@toggleActive'],

    // Membership sales (admin only)
    ['GET', '/admin/sales', 'SalesController@index'],
    ['POST', '/admin/sales', 'SalesController@store'],
    ['POST', '/admin/sales/{id}/toggle', 'SalesController@toggleActive'],
    ['POST', '/admin/sales/{id}/delete', 'SalesController@destroy'],
    ['POST', '/admin/sales/{id}/codes', 'SalesController@generateCode'],
    ['POST', '/admin/sale-codes', 'SalesController@generateStandaloneCode'],

    // Subscriptions (admin only)
    ['GET', '/admin/subscriptions', 'SubscriptionController@index'],
    ['POST', '/admin/subscriptions', 'SubscriptionController@store'],
    ['POST', '/admin/subscriptions/{id}/approve', 'SubscriptionController@approve'],
    ['POST', '/admin/subscriptions/{id}/cancel', 'SubscriptionController@cancel'],
    ['POST', '/admin/subscriptions/{id}/delete', 'SubscriptionController@destroy'],

    // Payment processors (admin only)
    ['GET', '/admin/payment-processors', 'PaymentProcessorsController@index'],
    ['POST', '/admin/payment-processors', 'PaymentProcessorsController@store'],
    ['POST', '/admin/payment-processors/{id}', 'PaymentProcessorsController@update'],
    ['POST', '/admin/payment-processors/{id}/toggle', 'PaymentProcessorsController@toggle'],
    ['POST', '/admin/payment-processors/{id}/delete', 'PaymentProcessorsController@destroy'],

    // Auto poster (admin only)
    ['GET', '/admin/auto-poster', 'AutoPosterController@index'],
    ['POST', '/admin/auto-poster/settings', 'AutoPosterController@saveSettings'],
    ['GET', '/admin/auto-poster/reddit/authorize', 'AutoPosterController@authorizeReddit'],
    ['GET', '/admin/auto-poster/reddit/callback', 'AutoPosterController@callbackReddit'],
    ['GET', '/admin/auto-poster/twitter/authorize', 'AutoPosterController@authorizeTwitter'],
    ['GET', '/admin/auto-poster/twitter/callback', 'AutoPosterController@callbackTwitter'],
    ['POST', '/admin/auto-poster/post/reddit', 'AutoPosterController@postReddit'],
    ['POST', '/admin/auto-poster/post/twitter', 'AutoPosterController@postTwitter'],
    ['POST', '/admin/auto-poster/clear-log', 'AutoPosterController@clearLog'],
];
