<?php

// Route table: [HTTP method, path pattern, Controller@action].
// {param} segments are captured and passed to the action by name.

return [
    // Public (guests can reach these)
    ['GET', '/health', 'HealthController@show'],
    ['GET', '/', 'AuthController@loginForm'],
    ['GET', '/terms', 'StaticPageController@terms'],
    ['GET', '/privacy', 'StaticPageController@privacy'],
    ['GET', '/about', 'StaticPageController@about'],
    ['GET', '/galleries', 'GalleryController@index'],
    ['GET', '/galleries/category/{slug}', 'GalleryController@category'],
    ['GET', '/galleries/{id}/photos', 'GalleryController@photosPage'],
    ['GET', '/galleries/{id}', 'GalleryController@show'],
    ['GET', '/images/{id}', 'ImageController@show'],
    ['GET', '/videos/{id}', 'VideoController@show'],
    ['GET', '/files/{file}', 'StorageController@serve'],

    // Biller postbacks (server-to-server; no session, no CSRF — see Router)
    ['GET', '/webhooks/{provider}', 'WebhookController@handle'],
    ['POST', '/webhooks/{provider}', 'WebhookController@handle'],

    // Auth
    ['GET', '/login', 'AuthController@loginForm'],
    ['POST', '/login', 'AuthController@login'],
    ['GET', '/login/2fa', 'AuthController@twoFactorForm'],
    ['POST', '/login/2fa', 'AuthController@twoFactorVerify'],
    ['GET', '/signup', 'AuthController@signupForm'],
    ['POST', '/signup', 'AuthController@signup'],
    ['GET', '/verify-email', 'AuthController@verifyEmail'],
    ['POST', '/verify-email/resend', 'AuthController@resendVerification'],
    ['POST', '/logout', 'AuthController@logout'],
    ['GET', '/forgot-password', 'AuthController@forgotForm'],
    ['POST', '/forgot-password', 'AuthController@forgot'],
    ['GET', '/reset-password', 'AuthController@resetForm'],
    ['POST', '/reset-password', 'AuthController@reset'],

    // Favorites (logged in)
    ['GET', '/favorites', 'FavoriteController@index'],
    ['POST', '/favorites/categories/{categoryId}/toggle', 'FavoriteController@toggle'],
    ['POST', '/favorites/galleries/{galleryId}/toggle', 'FavoriteController@toggleGallery'],

    // Saved searches (active members)
    ['GET', '/saved-searches', 'SavedSearchController@index'],
    ['POST', '/saved-searches', 'SavedSearchController@store'],
    ['POST', '/saved-searches/{id}/delete', 'SavedSearchController@destroy'],

    // Support (logged in)
    ['GET', '/support', 'SupportController@form'],
    ['POST', '/support', 'SupportController@submit'],
    ['GET', '/support/{id}', 'SupportController@show'],
    ['POST', '/support/{id}/reply', 'SupportController@reply'],

    // Admin
    // GET /admin is the admin entry point: it renders the login form for
    // anonymous visitors and the dashboard for logged-in admins, so it must
    // NOT be gated at the router level (the controller decides).
    ['GET', '/admin', 'AdminController@dashboard'],
    ['POST', '/admin', 'AdminController@login'],
    ['GET', '/admin/abandoned-uploads', 'AdminController@abandonedUploads', 'galleries'],
    ['POST', '/admin/abandoned-uploads/resume', 'AdminController@resumeAbandoned', 'galleries'],
    ['GET', '/admin/abandoned-uploads/{session}/{file}', 'AdminController@abandonedFile', 'galleries'],
    ['POST', '/admin/abandoned-uploads/{session}/{file}', 'AdminController@assignAbandoned', 'galleries'],
    ['GET', '/admin/search', 'SearchController@index', 'dashboard'],
    ['GET', '/admin/search.json', 'SearchController@suggest', 'dashboard'],
    ['GET', '/admin/categories', 'CategoryController@index', 'categories'],
    ['POST', '/admin/categories', 'CategoryController@store', 'categories'],
    ['GET', '/admin/categories/{id}/edit', 'CategoryController@edit', 'categories'],
    ['POST', '/admin/categories/{id}', 'CategoryController@update', 'categories'],
    ['POST', '/admin/categories/{id}/delete', 'CategoryController@destroy', 'categories'],
    ['GET', '/admin/galleries', 'AdminController@galleries', 'galleries'],
    ['GET', '/admin/galleries/create', 'GalleryController@create', 'galleries'],
    ['POST', '/admin/galleries/pending/upload', 'GalleryController@pendingUpload', 'galleries'],
    ['POST', '/admin/galleries/pending/chunk', 'GalleryController@chunkUpload', 'galleries'],
    ['POST', '/admin/galleries/pending/complete', 'GalleryController@chunkComplete', 'galleries'],
    ['POST', '/admin/galleries/pending/abort', 'GalleryController@chunkAbort', 'galleries'],
    ['POST', '/admin/galleries/pending/{file}/rotate', 'GalleryController@pendingRotate', 'galleries'],
    ['POST', '/admin/galleries/pending/{file}/delete', 'GalleryController@pendingDelete', 'galleries'],
    ['GET', '/admin/galleries/pending/{file}', 'GalleryController@pendingFile', 'galleries'],
    ['POST', '/admin/galleries', 'GalleryController@store', 'galleries'],
    ['GET', '/admin/galleries/{id}', 'AdminController@manageGallery', 'galleries'],
    ['GET', '/admin/galleries/{id}/edit', 'GalleryController@edit', 'galleries'],
    ['POST', '/admin/galleries/bulk', 'GalleryController@bulk', 'galleries'],
    ['POST', '/admin/galleries/{id}', 'GalleryController@update', 'galleries'],
    ['POST', '/admin/galleries/{id}/delete', 'GalleryController@destroy', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos', 'PhotoController@upload', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/caption', 'PhotoController@updateCaption', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/delete', 'PhotoController@destroy', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/move', 'PhotoController@move', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos/{photoId}/rotate', 'PhotoController@rotate', 'galleries'],
    ['POST', '/admin/galleries/{galleryId}/photos/bulk-rotate', 'PhotoController@bulkRotate', 'galleries'],
    ['GET', '/admin/photos/{id}/edit', 'PhotoController@edit', 'galleries'],
    ['POST', '/admin/photos/{id}/edit', 'PhotoController@applyEdit', 'galleries'],
    ['GET', '/admin/videos/{id}/edit', 'VideoEditorController@edit', 'videos'],
    ['GET', '/admin/videos', 'VideoEditorController@videoList', 'videos'],
    ['GET', '/admin/video-projects', 'VideoEditorController@dashboard', 'videos'],
    ['POST', '/admin/video-projects/{id}', 'VideoEditorController@save', 'videos'],
    ['POST', '/admin/video-projects/{id}/export', 'VideoEditorController@export', 'videos'],
    ['GET', '/admin/video-exports/{id}', 'VideoEditorController@status', 'videos'],
    ['GET', '/admin/video-exports/{id}/stream', 'VideoEditorController@stream', 'videos'],
    ['GET', '/admin/video-exports/{id}/download', 'VideoEditorController@download', 'videos'],
    ['POST', '/admin/video-exports/{id}/delete', 'VideoEditorController@deleteExport', 'videos'],
    ['POST', '/admin/video-exports/{id}/purge', 'VideoEditorController@purgeExport', 'videos'],
    ['GET', '/admin/video-exports/{id}/create-gallery', 'VideoEditorController@createGalleryFromExport', 'videos'],
    ['POST', '/admin/video-exports/{id}/create-gallery', 'VideoEditorController@createGalleryFromExport', 'videos'],

    // Users (admin only)
    ['GET', '/admin/users', 'UserController@index', 'users'],
    ['GET', '/admin/users/create', 'UserController@create', 'users'],
    ['POST', '/admin/users', 'UserController@store', 'users'],
    ['POST', '/admin/users/bulk', 'UserController@bulk', 'users'],
    ['POST', '/admin/users/{id}/impersonate', 'UserController@impersonate', 'users'],
    ['POST', '/admin/users/{id}/status', 'UserController@setStatus', 'users'],
    ['POST', '/admin/users/{id}/reset-password', 'UserController@resetPassword', 'users'],
    ['POST', '/admin/users/{id}/logout-everywhere', 'UserController@logoutEverywhere', 'users'],
    ['POST', '/admin/users/{id}/notes', 'UserController@addNote', 'users'],
    ['POST', '/admin/users/{id}/flag', 'UserController@setFlag', 'users'],
    ['POST', '/admin/users/{id}/role', 'UserController@updateRole', 'users'],
    ['GET', '/admin/users/{id}/edit', 'UserController@edit', 'users'],
    ['POST', '/admin/users/{id}', 'UserController@update', 'users'],
    ['POST', '/admin/users/{id}/delete', 'UserController@destroy', 'users'],
    ['GET', '/admin/users/{id}', 'UserController@show', 'users'],
    ['POST', '/admin/impersonate/exit', 'UserController@exitImpersonation'],

    // System maintenance (admin only)
    ['GET', '/admin/system', 'SystemController@index', 'dashboard'],
    ['POST', '/admin/system/cleanup/pending', 'SystemController@cleanupPending', 'dashboard'],
    ['POST', '/admin/system/cleanup/orphans', 'SystemController@cleanupOrphans', 'dashboard'],
    ['POST', '/admin/system/backup', 'SystemController@backupCreate', 'dashboard'],
    ['GET', '/admin/system/backups/{file}', 'SystemController@backupDownload', 'dashboard'],
    ['POST', '/admin/system/backups/{file}/delete', 'SystemController@backupDelete', 'dashboard'],
    ['POST', '/admin/system/variants', 'SystemController@variantsRegenerate', 'dashboard'],
    ['POST', '/admin/system/db/optimize', 'SystemController@dbOptimize', 'dashboard'],
    ['POST', '/admin/system/maintenance', 'SystemController@maintenanceToggle', 'dashboard'],
    ['POST', '/admin/system/housekeeping', 'SystemController@housekeepingRun', 'dashboard'],
    ['POST', '/admin/system/smtp-test', 'SystemController@smtpTest', 'dashboard'],
    ['POST', '/admin/system/cron-schedule/{job}', 'SystemController@saveCronSchedule', 'dashboard'],

    // Email server administration (admin only)
    ['GET', '/admin/mail', 'EmailController@index', 'dashboard'],
    ['POST', '/admin/mail/create', 'EmailController@create', 'dashboard'],
    ['POST', '/admin/mail/delete', 'EmailController@delete', 'dashboard'],
    ['POST', '/admin/mail/password', 'EmailController@password', 'dashboard'],
    ['POST', '/admin/mail/test', 'EmailController@smtpTest', 'dashboard'],
    // Test suite (admin only): page + real-time JSON polling + detached runner.
    ['GET', '/admin/test-suite', 'TestSuiteController@index', 'logs'],
    ['POST', '/admin/test-suite/run', 'TestSuiteController@run', 'logs'],
    ['GET', '/admin/test-suite/status', 'TestSuiteController@status', 'logs'],
    ['GET', '/admin/export/users', 'ExportController@users', 'users'],
    ['GET', '/admin/export/subscriptions', 'ExportController@subscriptions', 'membership'],

    // Unattended cron (secret-key protected, no session)
    ['GET', '/cron/housekeeping', 'CronController@run'],

    // Theme + docs (admin only)
    ['GET', '/admin/theme', 'ThemeController@index', 'theme'],
    ['POST', '/admin/theme', 'ThemeController@update', 'theme'],
    ['POST', '/admin/theme/presets/save', 'ThemeController@savePreset', 'theme'],
    ['POST', '/admin/theme/presets/apply', 'ThemeController@applyPreset', 'theme'],
    ['POST', '/admin/theme/presets/delete', 'ThemeController@deletePreset', 'theme'],
    ['GET', '/admin/site-editor', 'SiteEditorController@editor', 'site_editor'],
    ['GET', '/admin/site-editor/templates', 'SiteEditorController@templates', 'site_editor'],
    ['POST', '/admin/site-editor/save', 'SiteEditorController@save', 'site_editor'],
    ['POST', '/admin/site-editor/update/{id}', 'SiteEditorController@update', 'site_editor'],
    ['POST', '/admin/site-editor/delete/{id}', 'SiteEditorController@delete', 'site_editor'],
    ['POST', '/admin/site-editor/activate/{id}', 'SiteEditorController@activate', 'site_editor'],
    ['POST', '/admin/site-editor/deactivate', 'SiteEditorController@deactivate', 'site_editor'],
    ['GET', '/admin/help', 'HelpController@index', 'documentation'],
    ['GET', '/admin/support', 'SupportController@index', 'support'],
    ['GET', '/admin/support/{id}', 'SupportController@adminShow', 'support'],
    ['POST', '/admin/support/{id}/reply', 'SupportController@adminReply', 'support'],
    ['POST', '/admin/support/{id}/status', 'SupportController@status', 'support'],
    ['POST', '/admin/support/{id}/delete', 'SupportController@delete', 'support'],
    ['GET', '/admin/trends', 'TrendsController@index', 'trends'],
    ['POST', '/admin/trends/promote', 'TrendsController@approvePromotion', 'trends'],
    ['POST', '/admin/trends/dismiss', 'TrendsController@dismissPromotion', 'trends'],
    ['GET', '/admin/logs', 'LogsController@index', 'logs'],
    ['GET', '/admin/error-logs', 'LogsController@errorIndex', 'logs'],
    ['POST', '/admin/logs/{id}/rollback', 'LogsController@rollback', 'logs'],
    ['POST', '/admin/logs/{id}/purge', 'LogsController@purgeGallery', 'logs'],
    ['GET', '/admin/user-monitor', 'UserMonitorController@index', 'user_monitor'],

    // Settings (logged in)
    ['GET', '/settings', 'SettingsController@show'],
    ['POST', '/settings/password', 'SettingsController@updatePassword'],
    ['POST', '/settings/profile', 'SettingsController@updateProfile'],
    ['POST', '/settings/logout-everywhere', 'SettingsController@logoutEverywhere'],
    ['POST', '/settings/favorites', 'SettingsController@updateFavorites'],
    ['POST', '/settings/theme', 'SettingsController@updateTheme'],
    ['GET', '/settings/two-factor/setup', 'SettingsController@twoFactorSetup'],
    ['POST', '/settings/two-factor/enable', 'SettingsController@twoFactorEnable'],
    ['POST', '/settings/two-factor/disable', 'SettingsController@twoFactorDisable'],

    // Membership (logged in)
    ['GET', '/account', 'MembershipController@dashboard'],
    ['GET', '/membership', 'MembershipController@index'],
    ['GET', '/membership/my', 'MembershipController@my'],
    ['POST', '/membership/subscribe', 'MembershipController@subscribe'],
    ['POST', '/membership/cancel', 'MembershipController@cancel'],
    ['POST', '/membership/paypal-approve', 'MembershipController@paypalApprove'],
    ['GET', '/membership/checkout', 'MembershipController@braintreeCheckout'],
    ['GET', '/membership/braintree-token', 'MembershipController@braintreeToken'],
    ['POST', '/membership/braintree-token', 'MembershipController@braintreeToken'],

    // Plans (admin only)
    ['GET', '/admin/plans', 'PlanController@index', 'membership'],
    ['GET', '/admin/plans/create', 'PlanController@create', 'membership'],
    ['POST', '/admin/plans', 'PlanController@store', 'membership'],
    ['GET', '/admin/plans/{id}/edit', 'PlanController@edit', 'membership'],
    ['POST', '/admin/plans/{id}', 'PlanController@update', 'membership'],
    ['POST', '/admin/plans/{id}/delete', 'PlanController@destroy', 'membership'],
    ['POST', '/admin/plans/{id}/toggle-active', 'PlanController@toggleActive', 'membership'],

    // Membership sales (admin only)
    ['GET', '/admin/sales', 'SalesController@index', 'membership'],
    ['POST', '/admin/sales', 'SalesController@store', 'membership'],
    ['POST', '/admin/sales/{id}/toggle', 'SalesController@toggleActive', 'membership'],
    ['POST', '/admin/sales/{id}/delete', 'SalesController@destroy', 'membership'],
    ['POST', '/admin/sales/{id}/codes', 'SalesController@generateCode', 'membership'],
    ['POST', '/admin/sale-codes', 'SalesController@generateStandaloneCode', 'membership'],

    // Subscriptions (admin only)
    ['GET', '/admin/subscriptions', 'SubscriptionController@index', 'membership'],
    ['POST', '/admin/subscriptions', 'SubscriptionController@store', 'membership'],
    ['POST', '/admin/subscriptions/{id}/approve', 'SubscriptionController@approve', 'membership'],
    ['POST', '/admin/subscriptions/{id}/cancel', 'SubscriptionController@cancel', 'membership'],
    ['POST', '/admin/subscriptions/{id}/delete', 'SubscriptionController@destroy', 'membership'],

    // Payment processors (admin only)
    ['GET', '/admin/payment-processors', 'PaymentProcessorsController@index', 'payments'],
    ['POST', '/admin/payment-processors', 'PaymentProcessorsController@store', 'payments'],
    ['POST', '/admin/payment-processors/{id}', 'PaymentProcessorsController@update', 'payments'],
    ['POST', '/admin/payment-processors/{id}/toggle', 'PaymentProcessorsController@toggle', 'payments'],
    ['POST', '/admin/payment-processors/{id}/delete', 'PaymentProcessorsController@destroy', 'payments'],

    // Auto poster (admin only)
    ['GET', '/admin/auto-poster', 'AutoPosterController@index', 'autoposter'],
    ['POST', '/admin/auto-poster/settings', 'AutoPosterController@saveSettings', 'autoposter'],
    ['GET', '/admin/auto-poster/reddit/authorize', 'AutoPosterController@authorizeReddit', 'autoposter'],
    ['GET', '/admin/auto-poster/reddit/callback', 'AutoPosterController@callbackReddit', 'autoposter'],
    ['GET', '/admin/auto-poster/twitter/authorize', 'AutoPosterController@authorizeTwitter', 'autoposter'],
    ['GET', '/admin/auto-poster/twitter/callback', 'AutoPosterController@callbackTwitter', 'autoposter'],
    ['POST', '/admin/auto-poster/post/reddit', 'AutoPosterController@postReddit', 'autoposter'],
    ['POST', '/admin/auto-poster/post/twitter', 'AutoPosterController@postTwitter', 'autoposter'],
    ['POST', '/admin/auto-poster/queue/recommend', 'AutoPosterController@queueRecommendation', 'autoposter'],
    ['POST', '/admin/auto-poster/queue/post', 'AutoPosterController@postQueued', 'autoposter'],
    ['POST', '/admin/auto-poster/queue/retry', 'AutoPosterController@retryQueued', 'autoposter'],
    ['POST', '/admin/auto-poster/history/repost', 'AutoPosterController@repostPosted', 'autoposter'],
    ['POST', '/admin/auto-poster/history/reschedule', 'AutoPosterController@reschedulePosted'],
    ['POST', '/admin/auto-poster/history/edit', 'AutoPosterController@editPosted'],
    ['POST', '/admin/auto-poster/queue/post-all', 'AutoPosterController@postAllQueued'],
    ['POST', '/admin/auto-poster/queue/schedule', 'AutoPosterController@rescheduleQueued'],
    ['POST', '/admin/auto-poster/queue/dismiss', 'AutoPosterController@dismissQueued'],
    ['POST', '/admin/auto-poster/clear-log', 'AutoPosterController@clearLog'],
];
